### ISSUE TITLE
Daru::DataFrame::reindex_vectors! seems to not work properly

### ISSUE THREAD

**Issue by agisga** [v0dro/daru#10]
Reindexing with `Daru::DataFrame::reindex_vectors!` does not seem to work. Here is an example:

(1) Define a DataFrame

```Ruby
> df = Daru::DataFrame.new([[1,2,3],[13,13,13]], order: ['a','b']) 
=> 
#<Daru::DataFrame:70332675355200 @name = 662bfdbb-8894-49c6-92fc-a1f4d58e9a3c @size = 3>
                    a          b 
         0          1         13 
         1          2         13 
         2          3         13 
```

(2) Reindex the vectors using `df.reindex_vectors!([:b, :a])`

(3) Now, what was 'a' is 'b', and vice versa:

```Ruby
> df
=> 
#<Daru::DataFrame:70332675355200 @name = 662bfdbb-8894-49c6-92fc-a1f4d58e9a3c @size = 3>
                    b          a 
         0          1         13 
         1          2         13 
         2          3         13 
```

(4) But for some reason, when I try to access the vectors, I get the results according to the original indexing (prior to the reindexing):

```Ruby
> df[:a]
=> 
#<Daru::Vector:70332675314520 @name = nil @size = 3 >
    nil
  0   1
  1   2
  2   3

> df[:b]
=> 
#<Daru::Vector:70332675310020 @name = nil @size = 3 >
    nil
  0  13
  1  13
  2  13
```

(Additional problem) Assigning other indices than :a and :b doesn't work:

```Ruby
> df.reindex_vectors!([:x, :y])
=> #<Daru::Index:0x007fef341f34e0
 @index_class=Symbol,
 @relation_hash={:x=>nil, :y=>nil},
 @size=2>
> df
=> #<Daru::DataFrame:0x3ff79a217240>
```

**Comment by v0dro** [comment]
Thanks.

I'll fix that soon.

**Comment by v0dro** [comment]
I've fixed this in https://github.com/v0dro/daru/commit/0d9b71abd0db12e2913a2a4beef0b5d0fc274562.

Additionally I've made some behavioral changes where `reindex` will now preserve the labeling of the previous dataframe and insert `nil`s whenever a new index is encountered. For simply changing the index or vector you can now just use `#index=` or `#vectors=`. See [these tests for examples](https://github.com/v0dro/daru/blob/tseries/spec/dataframe_spec.rb#L1266).

Do test these new features and let me know if they're working as per what you're expecting. I'll close the issue after that.

**Comment by agisga** [comment]
Nice! This is great work! :)

One little issue I discovered while testing is that `#reindex` has side effects on the data frame that it is applied to. After application of `#reindex` with new indices, the original data frame is altered. Example:

```Ruby
[1] pry(main)> require 'daru'
=> true
[2] pry(main)> df = Daru::DataFrame.new([[1,2,3],['a','b','c']], order: [:num, :char])
=> 
#<Daru::DataFrame:69833817586200 @name = 87ca3c30-6f05-4ea2-9950-8ac6370910ee @size = 3>
                  num       char 
         0          1          a 
         1          2          b 
         2          3          c 

[3] pry(main)> df.reindex(Daru::Index.new([1,0,2,3,4,5,6]))
=> 
#<Daru::DataFrame:69833817681580 @name = 87ca3c30-6f05-4ea2-9950-8ac6370910ee @size = 7>
                  num       char 
         1          2          b 
         0          1          a 
         2          3          c 
         3        nil        nil 
         4        nil        nil 
         5        nil        nil 
         6        nil        nil 
```

So, a data frame with reordered rows and new nil-rows is returned. But the original frame now also has the nil rows; the reordering is not preserved in the original frame however:

```Ruby
[4] pry(main)> df
=> 
#<Daru::DataFrame:69833817586200 @name = 87ca3c30-6f05-4ea2-9950-8ac6370910ee @size = 7>
                  num       char 
         0          1          a 
         1          2          b 
         2          3          c 
         3        nil        nil 
         4        nil        nil 
         5        nil        nil 
         6        nil        nil 
```

I think if you want to preserve the new nil-rows in the original frame, then you should also preserve the reordering of the old rows. Although, I think it would be better if, `#reindex` had no side effects on the original frame.

`#reindex_columns` on the other hand does not have this kind of side effects. I think both methods need to be consistent with each other.

(On another note, you made the relevant pull request to the tseries branch, I don't know if that's intended. Also, it took me some time to figure out that I need to install gsl-nmatrix from your repository. Also, certain R packages need to be installed for all the spec to pass. I think it would be good to include installation instructions for the development version with such information :P )

**Comment by v0dro** [comment]
Thats a bug. Thank you!

**Comment by v0dro** [comment]
Ok problem solved - https://github.com/v0dro/daru/commit/d012457b61e4afd459e0cb41ac2e8c3a89b31ad0

**Comment by agisga** [comment]
Perfect :)

**Comment by v0dro** [comment]
Thank you :)
