### ISSUE TITLE
Data Frame vector initialization using ranges without using to_a

### ISSUE THREAD

**Issue by lokeshh** [v0dro/daru#112]
I think it would be great to have something like

```ruby
df = Daru::DataFrame.new({ a: 1..5 })
```
instead of 
```ruby
df = Daru::DataFrame.new({ a: (1..5).to_a })
```
What are your thoughts everybody?

**Comment by gnilrets** [comment]
Both forms work when I try them.

**Comment by v0dro** [comment]
Yep.

**Comment by lokeshh** [comment]
Sorry, I should have had a look carefully. How about making it work for index initialization. The following doesn't work:

```ruby
x = Daru::Index.new 1..5
```

**Comment by v0dro** [comment]
works!

**Comment by lokeshh** [comment]
Do you mean I should work on it to make it work or do you mean it is working?

It doesn't work for me, shows me the following error:

```ruby
[2] pry(main)> x = Daru::Index.new 1..5
NoMethodError: undefined method `[]' for 1..5:Range
from /home/ubuntu/workspace/daru/lib/daru/index.rb:27:in `new'
```

**Comment by v0dro** [comment]
I mean you working on it works fine. I know it doesn't work.
