### ISSUE TITLE
Daru::DataFrame methods involveing Daru::Vector extremely slow

### ISSUE THREAD

**Issue by agisga** [v0dro/daru#12]
I benchmarked `DataFrame` initialization from a Hash of Arrays

```Ruby
df = Daru::DataFrame.new({a: (1..10000).to_a, 
                          b: (1..10000).to_a,
                          c: (1..10000).to_a})
```

against an initialization from a Hash of `Daru::Vector`s

```Ruby
df = Daru::DataFrame.new({a: Daru::Vector.new((1..10000).to_a), 
                          b: Daru::Vector.new((1..10000).to_a),
                          c: Daru::Vector.new((1..10000).to_a)})
```

Then I appended a new column to the `DataFrame`, as an Array input and as a `Daru::Vector` input; i.e. `df[:d] = Daru::Vector.new((1..10000).to_a)` compared to `df[:e] = (1..10000).to_a`.

In both cases, the method involving a `Daru::Vector` is *extremely slow*. The above example with 10000 rows and 3 columns takes over 8 minutes on my Intel-core-i5-12GB-RAM-laptop. 

Here are the results:

```
*** Initialize a Daru::DataFrame ***
Using Array: 49.448592 milliseconds
Using Daru::Vector: 372070.893382 milliseconds
*** Append a new column ***
Using Daru::Vector: 123282.889606 milliseconds
Using Array: 12.778248000000001 milliseconds
```

(I am currently using the daru gem, because gsl-nmatrix fails to get installed on my machine for some reason. So, I'm sorry if this is already fixed in the most recent development version.)

**Comment by v0dro** [comment]
Over the top of my head I think this is happening because DataFrame tries to match elements with the same index and place them in the same row when a Daru::Vector is supplied. When an Array is supplied its just creating a Vector out of it and giving it the same index as the DataFrame.

I think this can be sped up for Vectors with same indexing, by first checking if indexes are the same for all the vectors and then avoiding index matching.

Thanks for this, I'll have a look soon.

**Comment by v0dro** [comment]
For temporary work around you can specify the option `clone: false` in the DataFrame constructor. This will avoid cloning the Vectors (if they have the same index) and prevent the index-by-index assignment that I'm talking about.

**Comment by v0dro** [comment]
I've optimized DataFrame creation when using Vectors of the same index. Please pull the latest code from the [`daru/tseries` branch](https://github.com/v0dro/daru/tree/tseries).

See the benchmarks for data frame creation here: https://github.com/v0dro/daru/blob/tseries/benchmarks/dataframe_creation.rb

**Comment by v0dro** [comment]
I've also sped up Vector assignment when the Vector has the same index as the DataFrame (https://github.com/v0dro/daru/commit/c63dcab803190aae7108341fdc8e6558ce05ed67).

See the benchmarks [here](https://github.com/v0dro/daru/blob/tseries/benchmarks/vector_assign.rb).

Speeding up assignment of differently indexed Vectors with the DataFrame will take time. I think I'll need to implement something like pandas' boolean indexing to make that happen. I'll look into that after GSOC.
