### ISSUE TITLE
Difference between single and multiple field selection

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#120]
So something like this surprised me today.  I converted some code that I had written that used multiple vector references to one that only used one and it broke.  Something like the following.  I understand why this is happening (df[:a,:b] returns a dataframe and df[:a] returns a vector).  Any ideas for how we could clean it up to behave more naturally?

````ruby
df = Daru::DataFrame.new({ a: 1.upto(2).to_a , b: 1.upto(2).to_a })
df_ab = df[:a,:b]
df_a = df[:a]

df_ab.group_by([:a]).size
df_a.group_by([:a]).size # => ArgumentError: wrong number of arguments (1 for 0)
````

**Comment by lokeshh** [comment]
Here's one crazy idea. Have df[:a] return a vector while df[[:a]], df[[:a, :b]] return dataframes.

**Comment by v0dro** [comment]
There can be a custom `group_by` method for Vectors too. Its giving the `ArgumentError` because I think it's reverting to `Enumerable#group_by`.

Lokesh your idea might confuse MultiIndex infrastructure.
