### ISSUE TITLE
[Cleanup] Drop unnecessary runtime dependencies

### ISSUE THREAD

**Issue by zverok** [v0dro/daru#139]
There are two ugly fat dependencies which currently prohibit usage of daru in small-scale projects:
* reportbuilder (which tugs rtf, prawn, and whatnot);
* spreedsheet (which tugs ruby-ole, and is fat enough on its own).

Both of them are absolutely not necessary for core daru functionality, so they should be documented as optional dependencies (like nyaplot or gnuplot) and not go into mandatory ones.

**Comment by v0dro** [comment]
Will do.
