### ISSUE TITLE
Use Guard for automatically running tests.

### ISSUE THREAD

**Issue by lokeshh** [v0dro/daru#157]
It would be great have something like [guard-spec](https://github.com/guard/guard-rspec) to automatically run the concerned specs whenever a change is made. This would **really** help to make TDD better.

**Comment by lokeshh** [comment]
Any suggestions? 

I was about to do it myself using `guard-rspec` but don't know how configure the `Guardfile`

**Comment by v0dro** [comment]
Why not use guard itself? We'll just need to figure it out. Don't think there's a need for a new gem.

**Comment by lokeshh** [comment]
Yes that's why I mean. Guard in not included as a gem in Daru yet.

**Comment by v0dro** [comment]
Sure. Make a separate PR.

**Comment by lokeshh** [comment]
This is done.
