### ISSUE TITLE
Introduce deprecation mechanizm

### ISSUE THREAD

**Issue by zverok** [v0dro/daru#162]
(Please, don't be angry at me!)

Development of Daru is a huge work, and it is research work mostly -- researching approaches, best and most effective APIs and so on. So, not always the very first version of some feature/API/approach is the best. But people are starting to use them, and it is not always easy to just say "guys, the things were changed and your code is not working anymore! Deal with it". On the other hand, there is not a good approach to always just add features and approaches, not removing any signs of older ones.

So, proposal here is to officialy start deprecating some of older features/approaches. Ruby's standard library already includes a [simple method](http://ruby-doc.org/stdlib-2.2.4/libdoc/rubygems/rdoc/Gem/Deprecate.html) to do so:

```ruby
class A
  extend Gem::Deprecate
  def foo1
  end

  def foo2
  end

  deprecate :foo1, :bar, 2016, 9
  deprecate :foo2, :none, 2017, 1
end

a = A.new
a.foo1
# NOTE: A#foo1 is deprecated; use bar instead. It will be removed on or after 2016-09-01.
# A#foo1 called from depr.rb:14.

a.foo2
# NOTE: A#foo2 is deprecated with no replacement. It will be removed on or after 2017-01-01.
# A#foo2 called from depr.rb:15.

```

To be honest, it is not the Best API Ever (I'd like to have date thing optional, and an ability to provide text comments to include in deprecation notices), but at least it is something to start with.

WDYT?

**Comment by v0dro** [comment]
Works! I would normally alias methods or keep the method and print into `STDERR` but this looks like a better way. Methods need to be deprecated carefully though.

**Comment by lokeshh** [comment]
Running `deprecate` gives me an error. Do we have to include any gem?

**Comment by lokeshh** [comment]
Oh Sorry! I just saw now that we have to do `extend Gem ::Deprecate`

**Comment by v0dro** [comment]
This has been introduced so I'm closing this issue.
