### ISSUE TITLE
DataFrame#clone not maintaining order of Vectors.

### ISSUE THREAD

**Issue by wlevine** [v0dro/daru#166]
```
[2] pry(main)> require 'daru'
=> true
[3] pry(main)> df = Daru::DataFrame.new({a: [-1,-2,-3,-4], b: [1,2,3,4]},order: [:b, :a])
=> 
#<Daru::DataFrame:47244265965420 @name = c580f1d5-30fc-4e12-a9ff-348783f3465a @size = 4>
                    b          a 
         0          1         -1 
         1          2         -2 
         2          3         -3 
         3          4         -4 

[4] pry(main)> df2 = df.clone
=> 
#<Daru::DataFrame:47244265576420 @name = 69020fd0-c640-4bb8-ade2-3a4d65fe75d2 @size = 4>
                    a          b 
         0          1         -1 
         1          2         -2 
         2          3         -3 
         3          4         -4 
```

The columns have the wrong label.

**Comment by lokeshh** [comment]
Changing `clone: false` to `clone: true` fixes the issue but @v0dro what does `clone` option do?

**Comment by v0dro** [comment]
@wlevine the `#clone` function is meant to be a 'shallow' copy of the dataframe. It does not copy the underlying vectors by default.

If you want a full copy use `DataFrame#dup`. Also close this issue if it solves your problem.

**Comment by v0dro** [comment]
@lokeshh The `clone` option specifies whether the Vectors are to be copied or not.

**Comment by v0dro** [comment]
If it's `true` the Vectors will be copied otherwise it will be a shallow copy.

**Comment by lokeshh** [comment]
@v0dro This might not be related to this issue but just to want to know these things-
- Should the order of dataframe be the same as that of hash when the dataframe is created from hash? 
- Should the order be preserved when the dataframe is cloned?

**Comment by v0dro** [comment]
> Should the order of dataframe be the same as that of hash when the dataframe is created from hash?
If you create a dataframe and don't specify the order, it will sort the keys alphabetically and the order will be alphabetical. However if you pass the `:order` option, it will adhere to `:order`.

> Should the order be preserved when the dataframe is cloned?
Yes it should be preserved.
