### ISSUE TITLE
Daru::Vector#tail broken

### ISSUE THREAD

**Issue by kylekyle** [v0dro/daru#17]
```ruby
> Daru::Vector.new([1,2,3]).tail(1)
=> TypeError: no implicit conversion from nil to integer
```

In the case of [`Vector#head`](16), you simply cannot request more elements than the `Vector` contains. I have yet to find a `Vector` instance for which `tail` works.

**Comment by v0dro** [comment]
Works in the latest development release: 

``` ruby

[1] pry(main)> Daru::Vector.new([1,2,3]).tail(1)
#=> 
##<Daru::Vector:92948220 @name = nil @size = 1 >
#   nil
# 2   3

```

Could you please clone from my master branch and use that? There are many bug fixes in it. The latest version will be out in a few days.
