### ISSUE TITLE
`#filter_rows` gets rid of vector names

### ISSUE THREAD

**Issue by agisga** [v0dro/daru#172]
Example:

```ruby
df1 = Daru::DataFrame.new a: 1..3, b: 4..6
df2 = df1.filter_rows { |r| r[:a] != 2 }
df1[:a].name
# => :a
df2[:a].name
# => nil
```

That is, the vectors of the returned data frame don't have names anymore.

**Comment by zverok** [comment]
#173 now, thanks :) I've procrastinated writing this proposal for several weeks.

**Comment by v0dro** [comment]
https://github.com/v0dro/daru/commit/dc53f4ee976185291b730119b00e3a56d52b3b25
