### ISSUE TITLE
Many-to-Many joins no longer work

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#178]
This test fails now:
https://github.com/v0dro/daru/commit/760fb19d5e65e1e4231777fdb18f8fd4284b6e79#diff-9a856a5cbb8265463fa1bb64f02258e1L33

**Comment by v0dro** [comment]
@zverok

**Comment by zverok** [comment]
Yeah, I see :( Sorry, guys, I'll fix today or tomorrow.
Shame on me.
