### ISSUE TITLE
rake all does not install dependencies

### ISSUE THREAD

**Issue by v0dro** [v0dro/daru#180]
Upon running `rake all` I got the following error: 

```
Could not find proper version of rake (10.5.0) in any of the sources
Run `bundle install` to install missing gems.
```

Ideally everything should be automated.

**Comment by v0dro** [comment]
Sounds good! Call it `rake spec setup` so it's obvious. The task for running specs can be renamed to `rake spec run`. This can be done by setting up rake to detect command line arguments: http://stackoverflow.com/questions/825748/how-do-i-pass-command-line-arguments-to-a-rake-task

**Comment by v0dro** [comment]
The default when running just `rake spec` should run both `rake spec setup` and `rake spec run`.

**Comment by lokeshh** [comment]
Would `rake spec run` run the specs for all Rubies. How will one run specs for only one Ruby version? Currently `rake run_all` run specs for all Rubies and `rake spec` run specs for only one Ruby version.

**Comment by v0dro** [comment]
Oh. Missed that. How about:
* `rake spec` runs the specs for only the current Ruby version (same behaviour as is right now).
*  `rake spec run all` running specs for all the Ruby versions.
* `rake spec run -v 2.2` will run specs for Ruby 2.2. You can of course put any version of Ruby there.
* `rake spec setup` does the test setup for all Ruby versions.

We'll just trust the user for running `rake spec setup` before running tests for all versions.

**Comment by lokeshh** [comment]
@v0dro Which answer are you referring to in the link: http://stackoverflow.com/questions/825748/how-do-i-pass-command-line-arguments-to-a-rake-task

The standard way of passing arguments to rake is something like `rake task[arg1, arg2]`.

**Comment by lokeshh** [comment]
Although using the trick mentioned in [this answer](http://stackoverflow.com/a/14078271/2623749) this is possible.

**Comment by v0dro** [comment]
Yeah I like the approach in the answer you posted more.

**Comment by lokeshh** [comment]
This issue is fixed.
