### ISSUE TITLE
Is there a way to easily transform an array of hash to DataFrame?

### ISSUE THREAD

**Issue by ShallmentMo** [v0dro/daru#185]
I have some JSON data like this: 
```
data = [{"code"=>"1"}, {"code"=>"2"}, {"code"=>"3"}]
```
And is there a way to easily transform an array of hash to DataFrame like this:
```
df = DataFrame(data, columns: ['code'])
```
just like what we can do in pandas of python.

**Comment by v0dro** [comment]
Yes.
``` ruby
2.2.1 :002 > a = data = [{"code"=>"1"}, {"code"=>"2"}, {"code"=>"3"}]
 => [{"code"=>"1"}, {"code"=>"2"}, {"code"=>"3"}] 
2.2.1 :003 > Daru::DataFrame.new(a)
 => #<Daru::DataFrame(3x1)>
      code
    0    1
    1    2
    2    3 
```

Go through the notebooks in the README for further information.

Also please direct further user level questions to the SciRuby mailing list: https://groups.google.com/forum/#!forum/sciruby-dev

**Comment by zverok** [comment]
I believe that just `DataFrame.new()` should work.

```ruby
Daru::DataFrame.new(data)
# => #<Daru::DataFrame(3x1)>
#      code
#    0    1
#    1    2
#    2    3 
```
