### ISSUE TITLE
Set a base category after ordering and renaming categories

### ISSUE THREAD

**Issue by lokeshh** [v0dro/daru#186]
There's is one enhancement and one bug with category data

1. The enhancement is that Daru should set the first category as base category after setting the category order.

2. The bug is that if base category is renamed then a new base category is not substituted in place of it.

**Comment by lokeshh** [comment]
3. Also need a function to remove unused categories.

**Comment by v0dro** [comment]
Could you split this into two different issues - one for the enhancement and one for the bug?

**Comment by lokeshh** [comment]
Splited it to three issues:

#190 #189 #188
