### ISSUE TITLE
Re assign base category on reordering

### ISSUE THREAD

**Issue by lokeshh** [v0dro/daru#190]
It makes sense to re assign base category after re-ording the categories. For example:

```ruby
?> dv = Daru::Vector.new [:a, :a, :b, :c], type: :category
=> #<Daru::Vector(4):cataegory>
   0   a
   1   a
   2   b
   3   c
>> dv.base_category
=> :a
>> dv.categories = [:c, :b, :a]
=> [:c, :b, :a]
>> dv.base_category
=> :a
```
It would be nice to have the base category set to `:c` because it occurs first in the new order.

**Comment by v0dro** [comment]
@agisga do you agree with this behavior? I will mark this as an enhancement if yes.

**Comment by agisga** [comment]
I think the suggested behavior is okay (I don't think this issue is very significant, because the user can set the desired base category by hand anyway).

**Comment by v0dro** [comment]
Ok cool.
