### ISSUE TITLE
Unexpected broken lines in dataframe display in iRuby

### ISSUE THREAD

**Issue by lokeshh** [v0dro/daru#191]
There are these random broken lines that are appearing at certain places. For example look at output of cell 6 of [this notebook](http://nbviewer.jupyter.org/github/lokeshh/sciruby-notebooks/blob/cat_notebooks/Data%20Analysis/Categorical%20Data/examples/%5BExample%5D%20Formula%20language%20in%20Statsample-GLM.ipynb)

**Comment by v0dro** [comment]
Cell 6 seems fine to me:
![screenshot from 2016-07-25 00 24 49](https://cloud.githubusercontent.com/assets/2629909/17085777/458142dc-51fe-11e6-9b23-62e43a85c64c.png)

**Comment by lokeshh** [comment]
![img](http://i64.tinypic.com/w8x1ys.png)

**Comment by v0dro** [comment]
That's weird. Can you write a similar HTML table and see if it displays correctly in the same environment?

**Comment by lokeshh** [comment]
I'm closing it for as I have lost access to my old linux environment. Will reopen once I set it up again.
