### ISSUE TITLE
Get rid of vector metadata

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#197]
This was my half-baked idea.  It didn't work out quite the way I wanted it to in the project I thought I needed it for so I'm not using it.  Probably best to get rid of it to remove bloat and let users handle metadata on their own.  Unless there are any objections, I'll try to find some time to remove it.

**Comment by zverok** [comment]
+1 for this. This was one of my first question when I've started to work with Daru.

**Comment by v0dro** [comment]
Ok works. Lets remove it.
