### ISSUE TITLE
if-then style syntax for easy assignment of values

### ISSUE THREAD

**Issue by v0dro** [v0dro/daru#209]
The `where` clause for DataFrame should be enhanced such that it supports assignment of particular values in a particular set of `Vector`s of the DataFrame.

For example, say we have this dataframe:
``` ruby
df = Daru::DataFrame.new({
  AAA: [1,3,5,6,7],
  BBB: ['a','b','c','d','e'],
  CCC: [-1,5,4,3,-3]
})
```

There should be a new `where=` method that takes a boolean index as first argument and name(s) of the columns as the second argument. The value to the RHS of the `=` will be assigned to whatever indexes are `true` in the boolean index that is in the first argument.

For example, given the above dataframe;
``` ruby
df.where(df.AAA >= 5, :CCC) = -1
```

....should yield the following dataframe:
``` ruby
df = Daru::DataFrame.new({
  AAA: [1,3,5,6,7],
  BBB: ['a','b','c','d','e'],
 CCC: [-1,5,-1,-1,-1]
})
```

It should also support assignments to multiple columns by allowing to pass an Array of Vector names to the second argument of `where`.

I'm also open to more clever ways of realizing this functionality.

**Comment by gnilrets** [comment]
Isn't this just....

````ruby
df.recode_rows do |row|
  row[:CCC] = -1 if row[:AAA] >= 5
  row
end
````

`recode_rows` is a lot more generic and flexible (although the current implementation is too slow).  For example, what if you want to assign multiple columns to different values based on some condition, or you want to set the value of some column to the value of another, if some condition is met, like:

````ruby
df.recode_rows do |row|
  if row[:AAA] >= 5
    row[:CCC] = 1
    row[:DDD] = row[:BBB]
  end
  row
end
````

I just wonder what is to be gained by adding another syntax for doing these kinds of things.

**Comment by zverok** [comment]
@gnilrets I guess problem is every other DataFrame library allows to do this. Maybe it is "just another syntax", but they would continue to ask, I suppose on those typical tables "pandas vs daru" we'll just look bad.

@v0dro I have a big consideration about the topic.

In fact I think @gnilrets is right in sense that designing new standalone feature is less useful approach than try to upgrade existing features the way that allows more flexibility and staff.

Applying this thought to idea of setting something on preselected part of dataframe, I'd propose the next example for consideration:
```ruby
df = Daru::DataFrame.new(
  AAA: [1,3,5,6,7],
  BBB: ['a','b','c','d','e'],
  CCC: [-1,5,4,3,-3]
)

df.select { |r| r.AAA >= 5 }.CCC =  -1
```

Let's take a look at its parts:
1. `df.select { |r| r.AAA >= 5 }` I'm seriously thinking we should not mimic this `where` thingy and try to stick with Ruby metaphors, not their poor Pythonic imitations;
2. `.CCC = -1` -- this should work also on entire DataFrame (`.column = value`), meaning "set all column values to this value";
3. How the entire line should work? I suppose, `df.select {}` (and other similar methods should return _view_ (some thing, that "remembers" source dataframe, but refers only to its part); it is powerful concept that will allow chaining of operations and look "natural" (at least for me):
```ruby
df.select { |r| r.AAA >= 5 }.reject { |r| r.BBB.empty? }.first(5).CCC =  -1
```

WDYT?

**Comment by v0dro** [comment]
Hmmmm makes sense. Closing this.
