### ISSUE TITLE
Installing daru on a fresh system

### ISSUE THREAD

**Issue by lokeshh** [v0dro/daru#214]
There are couple of problems faced after installing Daru on a new computer.

- It produces some `NameError`.

```ruby
NameError: uninitialized constant Daru::Accessors::ArrayWrapper::Forwardable
```
The above error goes away on installing `reportbuilder` gem

- Second is this one:

```ruby
2.3.0 :002 > dv = Daru::Vector.new [1, 2, 3]
 => #<Daru::Vector(3)>
   0   1
   1   2
   2   3 
2.3.0 :003 > dv.to_s
NameError: uninitialized constant Daru::Vector::ERB
```

This one is the cause of build failure in Statsample [here](https://github.com/SciRuby/statsample/pull/55).

It goes away after one do `require 'erb'`.

The issue can be reproduced doing the following:

1. rvm remove 2.3.0
2. rvm install 2.3.0
3. gem install daru
4. require 'daru'

[Here](https://gist.github.com/lokeshh/80bd64c72d5401028b541e03d4bb2263) are all error messages in detail.
Can we include a test in Travis CI to check for such things in future?

**Comment by v0dro** [comment]
> It produces some NameError.
> NameError: uninitialized constant Daru::Accessors::ArrayWrapper::Forwardable
> The above error goes away on installing reportbuilder gem

This should not have anything to do with reportbuilder. `ArrayWrapper` uses the [`Forwardable` module](https://github.com/v0dro/daru/blob/master/lib/daru/accessors/array_wrapper.rb#L6).

I changed that line to `::Forwardable` and added a `require 'forwardable` and it worked.

> It goes away after one do require 'erb'.
Did that too. Pushing in a while.

Need to think of a foolproof way of testing deployment of daru on new systems hmmm....

**Comment by v0dro** [comment]
Should be fixed with https://github.com/v0dro/daru/commit/be6cea41da684830b3eb012f6d660c52d47b2477
