### ISSUE TITLE
how to compare data from two dataframe

### ISSUE THREAD

**Issue by nvoynov** [v0dro/daru#22]
Hello, developers.

I try to use Daru::DataFrame for few tables, that are generated by another code. And now I need to compare two tables by id.

Suppose, I have two dataframes, one of them is loaded from csv file and another is empty generated

```
#<Daru::DataFrame:20391612 @name = old @size = 3>
           id field1 field2 field3 
     0   req1      1      2      3 
     1   req2      1      2      3 
     2   req3      1      2      3 

#<Daru::DataFrame:20391612 @name = new @size = 3>
           id field1 field2 field3 
     0   req1      nil      nil      nil 
     1   req2      nil      nil      nil
     2   req3      nil      nil      nil
     3   req4      nil      nil      nil
```

Is there any way to transfer\copy old [col][row] values from loaded data to newly generated? Something like 
```
  new[:req1][:field1] = old[:req1][:field1] unless old[:req1][:field1].nil?}
```
to get
```
#<Daru::DataFrame:20391612 @name = old @size = 3>
           id field1 field2 field3 
     0   req1      1      2      3 
     1   req2      1      2      3 
     2   req3      1      2      3 
     3   req4      nil    nil     nil
```

PS
Before this question I've written code by [row][col] index, but now I see that index don't write to csv and I haven't found a way to set index to Id column
```
      def copy(source)
        each_row_col_val {|row, col, val|
          @dataframe[col][row] = source[col][row] unless source[col][row].nil?
        }
      end

      def each_row_col_val(&block)
        rows = @dataframe.index.map.to_a
        cols = @dataframe.vectors.map.to_a
        rows.each {|row|
          cols.each {|col| yield(row, col, @dataframe[col][row]) if block_given?}
        }
      end
```

**Comment by v0dro** [comment]
To set a column to an index use the `#set_index` method - http://www.rubydoc.info/gems/daru/0.1.1/Daru/DataFrame#set_index-instance_method.

Pass in `keep: true` if you want to keep the column being assigned as the index.

As for copying, you directly copy whole rows from the old data frame to the new if it satisfies a given condition:

``` ruby

old.each_row_with_index do |row,n|
  new.row[n] = old.old[n] if some_condition(row)
end
```
