### ISSUE TITLE
#frequencies for non-category vector should be consistent with that of category vector

### ISSUE THREAD

**Issue by v0dro** [v0dro/daru#238]
For category:

``` ruby
2.2.1 :015 > v = Daru::Vector.new [1,2,2,1,3,4,2,3], type: :category
 => #<Daru::Vector(8):cataegory>
   0   1
   1   2
   2   2
   3   1
   4   3
   5   4
   6   2
   7   3 
2.2.1 :016 > v.frequencies
 => #<Daru::Vector(4)>
   1   2
   2   3
   3   2
   4   1 
```

For non-category:

``` ruby
2.2.1 :017 > a = Daru::Vector.new [1,2,2,1,3,4,2,3]
 => #<Daru::Vector(8)>
   0   1
   1   2
   2   2
   3   1
   4   3
   5   4
   6   2
   7   3 
2.2.1 :018 > a.frequencies
 => {1=>2, 2=>3, 3=>2, 4=>1} 
```

The `#frequencies` for non-category vectors should work in a similar manner as that for category vectors and both should be able to accept a `:hash` argument that will let them return a `Hash` containing the frequencies.

**Comment by lokeshh** [comment]
Can we skip the `:hash` argument because I one can always simply chain `to_h` at the end?

**Comment by v0dro** [comment]
Ok works. Don't have the `:hash` argument. But don't change any current behavior for category vectors, though.
