### ISSUE TITLE
SystemStackError for larger filters

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#240]
Something very bad is happening with filters.  I recently upgraded a bunch of my code to 0.1.4 and I started getting SystemStackErrors with some of my larger dataframes.  Here's how it can be reproduced:

````ruby
df = Daru::DataFrame.new({ a: [1] * 140_000 })
df.where(df[:a].eq(1))
#=>SystemStackError: stack level too deep
````

**Comment by v0dro** [comment]
Having a look.

**Comment by v0dro** [comment]
This error usually happens if a recursion is involved, but there is none here. Investigating now.

**Comment by v0dro** [comment]
@zverok @mrkn have you come across something like this before?

**Comment by v0dro** [comment]
Interesting answer: http://stackoverflow.com/questions/11544460/how-to-get-a-backtrace-from-a-systemstackerror-stack-level-too-deep

**Comment by v0dro** [comment]
@gnilrets I just learned about `caller.length` from that answer and it appears that the problem happens at the `Array#values_at` function called [here](https://github.com/v0dro/daru/blob/master/lib/daru/core/query.rb#L78).

``` ruby
[3] pry(main)> a = [1] * 140_000
[4] pry(main)> a.values_at(1,2,3)
=> [1, 1, 1]
[5] pry(main)> a.values_at([1,2,3]*100_000)
TypeError: no implicit conversion of Array into Integer
from (pry):5:in `values_at'
[6] pry(main)> a.values_at(*[1,2,3]*100_000)
SystemStackError: stack level too deep
from (pry):6:in `__pry__'
```

@mrkn I think we just found a bug in Ruby. It's probably a recursive call internally in MRI that is causing this bug.
