### ISSUE TITLE
conflict with NArray's NMatrix

### ISSUE THREAD

**Issue by kojix2** [v0dro/daru#27]
Hi @v0dro 

Thank you for your great gem!
But daru conflict with Tanaka's NArray. 
```
 Error:  /narray-0.6.1.1/nmatrix.rb:8:in `<top (required)>': uninitialized constant NArray (NameError)
```
daru.rb
```
lib_underscore = library.to_s.gsub(/-/, '\_').gsub('/', '\_')
create_has_library :'nmatrix/nmatrix'
```
daru/accessors/nmatrix_wrapper.rb
```
end if Daru.has_nmatrix_nmatrix?
```
This work. But not cool.

**Comment by v0dro** [comment]
Hmm thanks for reporting this. I havnt quite updated the nmatrix dependency every since the gem was newly updated.

We'll just need to change the `require 'nmatrix'` in daru to latest one that does not conflict with narray.

**Comment by v0dro** [comment]
Could send a PR changing `require 'nmatrix'` to `require 'nmatrix/nmatrix'`?
