### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Ch4s3** [v0dro/daru#3]
Would you ever consider adding a Singular value decomposition method? Its useful in latent semantic indexing among other things and there isn't currently a good plain ruby SVD implementation anywhere(that I can find.)

**Comment by v0dro** [comment]
I've added a `#to_nmatrix` method to `Daru::DataFrame` which converts a numerical DataFrame into an [NMatrix](https://github.com/SciRuby/nmatrix). 

NMatrix [implements SVD](https://github.com/SciRuby/nmatrix/blob/dc4b3d35eae270be6287379a2e117f3f68a2855b/lib/nmatrix/lapack.rb#L154) with the method `#gesvd` (basically exposes LAPACK gesvd to ruby), which you can then use for computing a singular value decomposition.

Hope this solves your problem :)

**Comment by Ch4s3** [comment]
I think that will completely solve my problem. I'll test it out in our gem and see if it works!
