### ISSUE TITLE
Poor scaling of filter functionality

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#32]
I'm finding really poor non-linear scaling with the filter functionality in a DataFrame.  Here's an example

````ruby
require 'daru'
require 'benchmark'

def bench(name, &block)
  time = Benchmark.realtime do
    yield block
  end
  puts "#{name}: #{time}"
end


bench :filter_example do
  df = nil
  bench :create_df do
    to_df = 1.upto(10).inject({}) { |h, icol| h["col#{icol}".to_sym] = 1.upto(10000).to_a; h }
    df = Daru::DataFrame.new(to_df)
  end

  0.upto(4).each do |i|
    n = 100*2**i
    bench "filter #{n}" do
      df.filter(:row) { |r| r[:col1] < n }
    end
  end
end
````

Results:
````
create_df: 0.101626406001742    
filter 100: 0.4592461759893922  
filter 200: 0.6331805069930851  
filter 400: 1.573929047997808   
filter 800: 5.534721941992757   
filter 1600: 24.703956208002637 
````

When the number of records retained doubles from 800 to 1600, the time required to filter increases by almost a factor of 5!

**Comment by gnilrets** [comment]
At least there is a workaround.  Instead of filtering the row, filter each vector individually and then recombine into a data frame:

````ruby
bench :filter_fast do
  df = nil
  bench :create_df do
    to_df = 1.upto(10).inject({}) { |h, icol| h["col#{icol}".to_sym] = 1.upto(10000).to_a; h }
    df = Daru::DataFrame.new(to_df)
  end


  0.upto(4).each do |i|
    n = 100*2**i
    bench "filter #{n}" do
      df[:_keep_row_] = Daru::Vector.new(1.upto(df.size).map { |idx| idx < n })
      Daru::DataFrame.new(
        df.vectors.inject({}) do |to_df, vec|
          to_df[vec] = df[vec].where(df[:_keep_row_])
          to_df
        end
      )
    end
  end
end
````

Result:
````
create_df: 0.10182627999165561   
filter 100: 0.04034803100512363  
filter 200: 0.0582550159888342   
filter 400: 0.06850832598865964  
filter 800: 0.06670019398734439  
filter 1600: 0.08262640700559132 
````

**Comment by v0dro** [comment]
Yes this mainly happens because filtering rows requires creating a new `Daru::Vector` object from each row, since the DataFrame is stored as columns internally.

An outstanding PR (https://github.com/v0dro/daru/pull/25) is trying to fix this but the current implementation might screw up non-numerical indexing.

A possible workaround might be simply passing an Array of boolean values to `#where`. Here are some benchmarks: https://github.com/v0dro/daru/blob/master/benchmarks/where_vs_filter.rb

**Comment by gnilrets** [comment]
Ah, looks like I missed using 'where' on a DataFrame.  Thanks!

**Comment by v0dro** [comment]
A possible fix would be first creating a Boolean index based on the runs of the blocks of the filter method, and then passing this to `where`. I have noticed that Boolean indexing works much faster in many cases.
