### ISSUE TITLE
Unexpected result of boolean operation between vectors

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#33]
````ruby
vtrue = Daru::Vector.new([true]*2)
vfalse = Daru::Vector.new([false]*2)

bool = (vfalse and vtrue)
````

The result is a vector where all of the elements are true, where I would expect all of them to be false.

**Comment by v0dro** [comment]
The `and` clause you're using is Ruby boolean `and`, which cannot be modified. Moreover such piecewise boolean operations aren't currently supported on Vector. Use a `Daru::Core::Query::BoolArray` for that. 

Or alternatively:
``` ruby

vtrue = Daru::Vector.new([true]*2)
vfalse = Daru::Vector.new([false]*2)

bool = (vfalse.eq(false).and(vtrue.eq(true)))
# OR
bool = (vfalse.eq(false) & vtrue.eq(true))
```

This operation will return a `BoolArray`.

**Comment by gnilrets** [comment]
Thanks, this works
