### ISSUE TITLE
Is dup working properly?

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#36]
Given
````ruby
v1 = Daru::Vector.new(1.upto(5).to_a)
df1 = Daru::DataFrame.new(v1: v1)
````

I would expect that `dup` would create a new dataframe object with new vectors.  However, if I recode the vector in `df1`, the vector in `df2` is changed too.
````ruby
df2 = df1.dup

df1[:v1].recode! { |v| v * 2 }
df2[:v1] == df1[:v1]
````
Returns `true` when I would expect it to return `false`.

I can get the result I want if I `dup` each vector individually.  But this is cumbersome when I've got a larger dataframe.
````ruby
df2 = df1.dup
df2[:v1] = df1[:v1].dup

df1[:v1].recode! { |v| v * 2 }
df2[:v1] == df1[:v1]
````
Returns `false` as expected.

**Comment by v0dro** [comment]
Ok we're using [`to_a` in dup](https://github.com/v0dro/daru/blob/master/lib/daru/dataframe.rb#L436) and I just realized that when you're using `Array#to_a` returns the same Array and not a duplicate.

Adding a `dup` ahead of the `to_a` should fix this. Could you send me a PR? Also add a test?

Thanks for reporting.
