### ISSUE TITLE
Add Travis badge to README

### ISSUE THREAD

**Issue by agarie** [v0dro/daru#4]
See title.

**Comment by v0dro** [comment]
Its there! https://github.com/v0dro/daru#daru

The build is errored because I'm pointing to gsl-nmatrix and statsample from my local computer sources. Will fix that to use git soon.

**Comment by agarie** [comment]
Err, my mistake. I could sweat I didn't see the icon when I looked at the README. (maybe it didn't load or something)

**Comment by v0dro** [comment]
yeah it takes time to load :P
