### ISSUE TITLE
Daru::Core::GroupBy#apply_method sometimes chokes on nils

### ISSUE THREAD

**Issue by sebastianiorga** [v0dro/daru#44]
Using `daru` from the master branch on github.
Example:

```ruby
$> d = Daru::DataFrame.new({ key: [:a, :b, :c, :b], val: [1, nil, nil, 2] })
=> 
#<Daru::DataFrame:42220140 @name = 2ff8be51-8af2-4a10-8ea9-248409523960 @size = 4>
                  key        val 
         0          a          1 
         1          b        nil 
         2          c        nil 
         3          b          2 

$> d.pivot_table(index: [:key])
NoMethodError: undefined method `mean' for nil:NilClass
from /home/seb/.rvm/gems/ruby-2.2.1/bundler/gems/daru-99db9f85ab6e/lib/daru/core/group_by.rb:228:in `block (2 levels) in apply_method'
[6] pry(#<#<Class:0x007fd28039b110>>)> 
```

Things that combine to cause the problem:
1. `Vector#[]` returns a value when it receives a single integer index
2. `GroupBy#apply_method`, for this example, `@groups` is set to `{[:a]=>[0], [:b]=>[1, 3], [:c]=>[2]}
` so the call below to `slice = vec[*indexes]` just passes one value.
3. The next line, `daru/core/group_by.rb @ line 228`: `single_row << (slice.is_a?(Numeric) ? slice : slice.send(method))` presumably assumes that if slice is not a numeric it must be an Enumerable? Regardless it explodes when it gets a single nil.

I'm not sure what the correct fix is. Some ideas: 
1. Vector#[] could always return a Vector. That's a consistency plus, but probably a usability hit since extracting the value easily is nice.
2. Guard against `nil` in `GroupBy#apply_method` and just append `nil` to `single_row` if `slice.nil?`. Or something along those lines?
3. It seems like the existing check, at `daru/core/group_by.rb @ line 228` is essentially a type check to see if the slice is an `Enumerable` or not. Maybe just have it be `single_row << (slice.is_a?(Enumerable) ? slice.send(method)) : slice`. 

Just getting started with Daru so not sure if `Vector#[]` returning a bare `nil` causes issues elsewhere. I've added fix 3. to my fork and will see if it ends up breaking other things as I do more stuff based on pivot tables. The tests are green for what that matters.

**Comment by v0dro** [comment]
Thanks for raising this issue. Will look into it ASAP.

**Comment by lokeshh** [comment]
Fix 3 seems plausible to me since `Daru::Vector` know well to handle nils in methods such as `:mean`, `:sum`. For some methods such as `:min`, `:max` Daru shows an error because those methods do not handle nils. I propose we use fix 3 and make change in methods such as `:min` and `:max` so that they support computation with nils. 

Pandas have the same behavior. For example:
```python
>>> a = pd.Series( [1, 2, 3, np.nan])                                             
>>> a.max()
3.0
>>> a.min()
1.0
```
