### ISSUE TITLE
Vector.uniq not working when pulling vector from DataFrame

### ISSUE THREAD

**Issue by dansbits** [v0dro/daru#64]
I'm getting an exception when I try to find unique values from a column in a data frame. My data frame is built from a csv similar to this:

```
PO_NAME	STATE	ZCTA	ZIP	ZIP_TYPE
Merizo	GU	96916	96916	Post Office or large volume customer
Inarajan	GU	96917	96917	Post Office or large volume customer
Agat 	GU	96928	96928	Post Office or large volume customer
```
An excel version of the data can be found here: http://www.udsmapper.org/zcta-crosswalk.cfm

If I run the following code:
```
zip_to_zcta = Daru::DataFrame.from_csv('~/data/zip_to_zcta.csv')
zip_to_zcta['ZIP'].uniq
```
I get the following error:
````
IndexError: Expected index size >= vector size. Index size : 41038, vector size : 41270
````

**Comment by v0dro** [comment]
@Deepakkoli93 @lokeshh you want to have a look at this one? It's mostly to do with `Vector#uniq`.

**Comment by Deepakkoli93** [comment]
i'll have a look at it.

**Comment by Deepakkoli93** [comment]
@v0dro I think the `Vector#uniq` method is not removing duplicates. 
```ruby
    def uniq
      uniq_vector = @data.uniq
      pp uniq_vector
      new_index   = uniq_vector.inject([]) do |acc, element|
        acc << index_of(element)
        acc
      end
      Daru::Vector.new uniq_vector, name: @name, index: new_index, dtype: @dtype
    end
```  

I ran the code posted by OP printed `uniq_vector` and saw that there are some duplicates of the form 850 and 850.0, 820 and 820.0 etc.

Any suggestions?

**Comment by Deepakkoli93** [comment]
`@data.uniq` inside `Vector#uniq` is not removing duplicates to be precise

**Comment by v0dro** [comment]
@Deepakkoli93 `850` and `850.0` are different objects. Them not being removed by `#uniq` is normal.
``` ruby
a = [2, 2.0]
# [2, 2.0]
a.uniq
=> [2, 2.0]
```
 The problem is that the `index_of` method is returning is the same result for both `2` and `2.0`:

``` ruby
v = Daru::Vector.new([2,2.0,4,4.0], index: [:a, :b, :c, :d])
v.send(:index_of, 2)
# => :a
v.send(:index_of, 2.0)
# => :a
```

The problem is that we're using `Array#index` internally which evaluates `2 == 2.0` as `true` and gives wrong result. Can you think of a work around for that?

And btw, if you're thinking of applying for GSOC, coming up with your own solutions to problems is one of the fundamental abilities that we assess.

**Comment by Deepakkoli93** [comment]
Modifying `index_of` as follows did the trick
``` ruby
    def index_of element
      @index.key @data.index{|x| x.eql? element}
    end
```

**Comment by dansbits** [comment]
@Deepakkoli93 thanks for looking into this!
