### ISSUE TITLE
Covariance calculation seems wrong

### ISSUE THREAD

**Issue by mohawkjohn** [v0dro/daru#7]
```
[52] pry(main)> dd.cov
=>
#<Daru::DataFrame:70361442947720 @name = ade7e257-db8a-467e-9a02-6d14e9ad824d @size = 3>
                   ax         ay         az
        ax 0.00014379 -1.0361854 -7.3389159
        ay -1.0361854 0.00012949 -3.6098704
        az -7.3389159 -3.6098704 7.21220195

pry(main)> dd.min
=>
#<Daru::Vector:70361441216360 @name = nil @size = 3 >
                                      nil
                  ax -0.03294628633705924
                  ay -0.02795710559369226
                  az -0.02536420404774847

pry(main)> dd.max
=>
#<Daru::Vector:70361441840300 @name = nil @size = 3 >
                                      nil
                  ax  0.03276209162313101
                  ay  0.03073589051661277
                  az 0.024760295165908133

pry(main)> dd.std
=>
#<Daru::Vector:70361441679800 @name = nil @size = 3 >
                                      nil
                  ax 0.011991490010508732
                  ay 0.011379778474542456
                  az 0.008492468398766329
```

I'm fairly certain the covariance for the third row/column (:az) is wrong here.

**Comment by v0dro** [comment]
Could you please provide me with your testing data so that I can write a test for that and verify it with R or octave?

**Comment by v0dro** [comment]
I've written some tests and amended the algorithm in https://github.com/v0dro/daru/commit/e8d45b09864777b8554f946a6135cc206e073a01.

Could you give it a shot?

**Comment by mohawkjohn** [comment]
I'm not quite sure how to install Daru from source. There's no rake install task.

**Comment by agarie** [comment]
Hey Sameer, you probably should add `require 'bundle/gem_tasks'` to the Rakefile. It adds tasks for building, installing and releasing the gem.

**Comment by v0dro** [comment]
@agarie  ok I'll do that.

@mohawkjohn for now you can clone the repo, do a `gem build daru.gemspec` and then `gem install daru-0.0.5.gem`.

**Comment by v0dro** [comment]
@mohawkjohn could you test this once more so that I can close the issue?. `rake install` will work now.

**Comment by mohawkjohn** [comment]
Thanks, yes, it's fixed!
