### ISSUE TITLE
Sorting a sorted dataframe produces the wrong result

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#74]
Applying a sort multiple times to a dataframe gives different results.

````ruby
df = Daru::DataFrame.new({ a: [3,1,2] })
puts df.sort!([:a]).to_hash
puts df.sort!([:a]).to_hash
````

output:
````
{:a=>
#<Daru::Vector:70293990504740 @name = a @size = 3 >
      a
  1   1
  2   2
  0   3
}
{:a=>
#<Daru::Vector:70293990504740 @name = a @size = 3 >
      a
  2   2
  0   3
  1   1
}
````

**Comment by gnilrets** [comment]
This was using Daru 0.1.2.  I just tested this using the current master branch and it works as expected (and is tremendously faster to boot!).  I would really appreciate a release as soon as you think it's ready.

**Comment by v0dro** [comment]
Ok will do. @lokeshh is yet make some docs fixes in order to reflect the latest changes to sorting. I'll bump to 0.1.3 once he does that.

**Comment by gnilrets** [comment]
Thanks!
