### ISSUE TITLE
Daru::Index#[] not returning proper sub-Vector on Integer Index

### ISSUE THREAD

**Issue by shreyanshd** [v0dro/daru#78]
On a Daru::Vector with index of datatype Integer, #[] method doesn't return the required Daru::Vector on passing Range as a parameter.

Here's an example

```ruby
In [3]: require 'daru'
index = Daru::Index.new([5,4,3,2,1])
vector = Daru::Vector.new(['five','four','three','two','one'], name: "TestVector", index: index)
   ...: 
Out[3]: 

#<Daru::Vector:70133768745100 @name = TestVector @size = 5 >
           TestVector
         5       five
         4       four
         3      three
         2        two
         1        one


In [4]: vector[5..3]
   ...: 
Out[4]: 

#<Daru::Vector:70133765384060 @name = TestVector @size = 0 >
           TestVector

```

But on passing range (0,3) it is giving the necessary Vector.
```ruby
In [5]: vector[0..3]
   ...: 
Out[5]: 

#<Daru::Vector:70133765251080 @name = TestVector @size = 4 >
           TestVector
         5       five
         4       four
         3      three
         2        two

``` 
Daru::Index#[] method is assuming that since the index is of type Integer, it is handling it as the default indexing scheme starting from 0.
But it is not the case here.

Is this kind of implementation intentional and necessary? @v0dro

**Comment by v0dro** [comment]
It's supposed to be that way unless we find special use cases where the integer index needs to be that way.
