### ISSUE TITLE
Daru::VERSION should give which version is being used

### ISSUE THREAD

**Issue by mohawkjohn** [v0dro/daru#8]
This enables you to check that you're using the version you think you're using from within IRB/Pry/iruby.

**Comment by v0dro** [comment]
This is working for me:

```

[1] pry(main)> require 'daru'
=> true
[2] pry(main)> Daru::VERSION
=> "0.0.5"
```

Though I think this was being referred to from the gemspec so I've explicitly required `daru/version.rb` now.
