### ISSUE TITLE
Vector metadata feature

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#81]
I'd like to be able to associate arbitrary metadata with vectors in a way that as vectors get duped and passed around between dataframes, their metadata remains intact.  A use case would be that I read a date from a CSV file.  Some of the dates may be invalid or contain special characters, so I need to start out by just reading it as a string.  Then after some cleaning and error handling, I want to enforce that the vector is actually meant to be parsed as a date with a format specified in the metadata.

Thoughts?

**Comment by v0dro** [comment]
Sounds good. Can you give code samples of your intended API?

As a start, I think you can specify the metadata behavior with lambdas which are run when a specific type of data (in your case inside a string) occurs.

**Comment by gnilrets** [comment]
Just an idea at this point that I thought would help DRY up some code I'm using with Daru.  If you're on board I'll work on something that could integrate with Daru.

**Comment by v0dro** [comment]
Sure. But do keep it such that it does not affect the current functionality.
