### ISSUE TITLE
Documentation style

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#86]
I'm only familiar with TomDoc (http://tomdoc.org/).  It looks like there might be two different styles of documentation going on (e.g., these two look very different to me: https://github.com/v0dro/daru/blob/master/lib/daru/dataframe.rb#L51, https://github.com/v0dro/daru/blob/master/lib/daru/dataframe.rb#L64).

Is there a convention you'd like to follow?

**Comment by v0dro** [comment]
The first style is result of direct porting from statsample. The second is the one that is newly written and is to be followed in all future releases.

**Comment by v0dro** [comment]
The first style is result of direct porting from statsample. The second is the one that is newly written and is to be followed in all future releases.

**Comment by gnilrets** [comment]
There's a plugin - https://github.com/rubyworks/yard-tomdoc

**Comment by v0dro** [comment]
Will this work on rubygems? I think we should stick to YARD for docs since it's very extensible and the tagging syntax is great for specifying how exactly you want your docs to render.

**Comment by v0dro** [comment]
Check this out - http://gnuu.org/2010/05/12/whats-missing-from-tomdoc/

**Comment by gnilrets** [comment]
I'm totally fine sticking with YARD.  I just haven't used it before so I've got a bit of research to do.

**Comment by lokeshh** [comment]
@gnilrets One command that might be very helpful if you can't seen it already is `yard server --reload`. It let's you see the changes you make in documentation instantly.
