### ISSUE TITLE
Support categorical variables

### ISSUE THREAD

**Issue by v0dro** [v0dro/daru#9]
Currently the only types of data supported by daru are numeric (incorporating all sorts of Numeric data - ordinal, nominal, categorical, etc...) and object (stuff like Strings, symbols, etc.).

Having a separate data type for categorical data would be very helpful for statistical computations. Maybe something similar to [pandas.Categorical](http://pandas-docs.github.io/pandas-docs-travis/categorical.html).

**Comment by lokeshh** [comment]
This is done :)
